### ISSUE TITLE
有考虑，提供 自动格式修复 功能吗

### ISSUE THREAD

**Issue by chinanf-boy** [hustcc/hint#4]

**Comment by hustcc** [comment]
这个工具，可能需要重构下！

fixed 功能是可以做的！

**Comment by chinanf-boy** [comment]
https://github.com/chinanf-boy/explain-translateMds/issues/1

这个错误❌，其实才是我找 lint 工具的 原因

**Comment by hustcc** [comment]
不允许输入特殊字符？抽象下这个问题是什么意思？

**Comment by chinanf-boy** [comment]
ISSUE 写的很明白了啦

就是 在 `sublime` 中 显示 `BS` 的字样

但是` Vscode `中却没有占位

我也不知道自己怎么打出来的,

不过应该是，在中英文打字-切换-出现的错误

**Comment by hustcc** [comment]
然后需要 lint 来提示这个字符错误？

**Comment by chinanf-boy** [comment]
yes - 不过只是这么提一下

remark - https://github.com/remarkjs/remark

也提供 md 格式检测，不过对中英文字符不太支持

- 没有占位的符号在 `vscode` 应该算是个 `Bug`

- 还有就是，提示-> 不如直接->修正 - 懒人都如此

**Comment by 40huo** [comment]
修复功能是个很常用的需求，以前有一个 zhlint 工具，不过好久没有维护了。
