### ISSUE TITLE
Windows 下读取文件出现编码错误 && 公式中忽略 E205

### ISSUE THREAD

**Issue by 40huo** [hustcc/hint#5]
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 18: illegal multibyte sequence
```
Python 3.6
可能要在读文件的地方加上 `encoding=utf-8`，或者添加文件编码检测的功能。

另外，在形如
```markdown
$ a + b = c $

$$
a + b = c
$$
```
这样的公式中应该忽略 E205 的检测。

**Comment by hustcc** [comment]
请使用重构版本，基于 ast 便于扩展。https://github.com/hustcc/lint-md

**Comment by hustcc** [comment]
请使用重构版本，基于 ast 便于扩展。https://github.com/hustcc/lint-md
